### ISSUE TITLE
Voice over with premade ElevenLabs voices

### ISSUE THREAD

**Issue by ghost** [pnkvalavala/Multivoice#1]
Is there a way i could use it as Voice-Over with premade ElevenLabs voice?
Not the dubbing, but over the sound voice-over with premade voice?

**Comment by pnkvalavala** [comment]
Absolutely! You can use pre-made ElevenLabs voices for voice-over in Multivoice. Simply use the id of the voice you want to configure.

Let me know if you have any more questions or need further assistance!

**Comment by ghost** [comment]
I have installed your repo, please give me example what i should change and where to use one premade voice for the whole video as voice over. Where should I put id, what id etc. I used id from https://api.elevenlabs.io/v1/voices and it didn't work. I downloaded sample and put it in voice_clones. Also, to be clear, i don't what it to translate, **i just want it to read the subtitles i provide at the specific times**. I can even overlay the voice in videoeditor myself, i just want it to read the subtitles at specific times. The best way would be if you just show me on an example, if you don't mind.

**Comment by pnkvalavala** [comment]
Certainly! To use a pre-made ElevenLabs voice in Multivoice, follow these steps:

1. Open the [tts.py](https://github.com/pnkvalavala/Multivoice/blob/main/tts.py) file in the Multivoice repository.

2. Within the `tts` function, check for `url` where voice is configured. It may look something like this:

    ``` python
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{id}"
    ```

3. Replace the `id` with the ID of the pre-made ElevenLabs voice you want to use. You can find the available voice IDs in the [ElevenLabs documentation](https://elevenlabs.io/docs/api-reference/text-to-speech).

4. Since you are using a default voice for the entire video, you can bypass the step of uploading an audio file and extracting voice IDs for each user. You may need to make additional tweaks in the code to handle this scenario, such as skipping the audio extraction and voice cloning steps.

**Comment by ghost** [comment]
https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM

KeyError: 'voice_id'
Traceback:
```
File "C:\Users\Win10\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Win10\Multivoice\app.py", line 45, in <module>
    clone()
File "C:\Users\Win10\Multivoice\voiceclone.py", line 32, in clone
    cloned_voice_id = response.json()['voice_id']
```

**Comment by livefrommin** [comment]
`cloned_voice_id = response.json()['voice_id']`
That's appears if you haven't subscription to elevenlabs or, if you use starter subscription - you've tried to clone more then 10 voices
